# Generated by Django 5.0.3 on 2024-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('surname1', models.CharField(max_length=40)),
                ('surname2', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=55)),
                ('course', models.CharField(max_length=25)),
                ('moduls', models.CharField(max_length=50)),
                ('tutor', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=2)),
                ('rol', models.CharField(choices=[('student', 'student'), ('professor', 'professor')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('surname1', models.CharField(max_length=40)),
                ('surname2', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=55)),
                ('course', models.CharField(max_length=25)),
                ('moduls', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('student', 'student'), ('professor', 'professor')], max_length=25)),
            ],
        ),
    ]
